### ISSUE TITLE
Create api call

### ISSUE THREAD

**Issue by geoffreycc** [wortleyjk-codefellows/Sea301N3-FinalProject#20]

**Comment by spamalope01** [comment]
I have completed about 99% of the api call.  I have it returning information, i just need to finish the request where we tell it only 'seniors' and the location zip code.  

Secondly, I will create a new api to pull in the random pets that we're going to display on the landing page when the user is in desktop mode.

**Comment by spamalope01** [comment]
I have the selective and random API's pulling back the appropriate data.  will create new issue for pushing that information to the appropriate page.
